wandb:
  entity: paradigms-team
  project: DonkeyKongPretrainings
  run_name: inverse_dynamics_v2
  enabled: true

pretrain:
  total_steps: 100000
  save_every_steps: 10000
  learning_rate: 1e-4
  head_hidden_dim: 512
  log_interval: 500
  dataset_chunk_size: 2048
  save_dataset: true
  action_repeat_steps: 4
  seed: 42
